# Generated by Django 5.1 on 2025-01-09 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID новости')),
                ('title', models.CharField(help_text='Введите заголовок новости (до 100 символов)', max_length=100, unique=True, verbose_name='Заголовок новости')),
                ('little_content', models.TextField(help_text='Введите краткое описание новости (до 200 символов)', max_length=200, unique=True, verbose_name='Краткое описание новости')),
                ('content', models.TextField(help_text='Введите основной текст новости', verbose_name='Основной текст новости')),
                ('published_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('author', models.CharField(blank=True, help_text='Введите Ф.И.О. автора новости', max_length=100, verbose_name='Автор новости')),
                ('category', models.CharField(choices=[('university', 'Университет'), ('student_life', 'Студенческая жизнь'), ('it', 'IT и технологии'), ('health', 'Здоровье'), ('science', 'Наука'), ('events', 'События'), ('sports', 'Спорт'), ('economy', 'Экономика')], help_text='Введите категорию новости', max_length=100, verbose_name='Категория')),
                ('image_url', models.ImageField(blank=True, help_text='Загрузите изображение для новости', null=True, upload_to='images/', verbose_name='Изображение новости')),
                ('is_published', models.BooleanField(default=False, help_text='Нажмите, если нужно опубликовать новость', verbose_name='Публикация новости')),
                ('views', models.IntegerField(default=0, help_text='Количество просмотров', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
