# Generated by Django 5.1 on 2025-01-09 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Введите основной текст новости', verbose_name='Основной текст новости'),
        ),
    ]
