# Generated by Django 5.1 on 2025-01-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='little_content',
            field=models.TextField(help_text='Введите краткое описание новости (до 500 символов)', max_length=500, unique=True, verbose_name='Краткое описание новости'),
        ),
    ]
